on:
  push:
    branches-ignore:
      - main
      - ghpages

name: "check package with checklist"

jobs:
  check-package:
    runs-on: ubuntu-latest
    name: "check package"
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      N2KBUCKET: ${{ secrets.N2KBUCKET }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::347082780157:role/inbo-n2kmonitoring-shared-infra-eu-west-1-unittest-role
          aws-region: eu-west-1
      - uses: inbo/actions/check_pkg@main
