on:
  push:
    branches:
      - main
      - master
permissions:
  contents: write

name: "check package on main with checklist"

jobs:
  check-package:
    runs-on: ubuntu-latest
    name: "check package"
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      N2KBUCKET: ${{ secrets.N2KBUCKET }}
    steps:
      - uses: inbo/actions/check_pkg@checklist-0.3.6
