on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '6 0 15 * *'

name: "check package on main"

jobs:
  check-package:
    runs-on: ubuntu-latest
    name: "check package"
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      ORCID_TOKEN: ${{ secrets.ORCID_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: inbo/actions/check_pkg@master
        with:
          token: ${{ secrets.PAT }}
